Repository silent-readers/joogobooks_back, pull requests merged in 2023-09, with the labels that each got.

#43 ♻️ nickname 필드 Profile -> User
  book/models.py
  user/models.py
  user/serializers.py
  user/views.py
Labels: Refator

#44 Recommend
  chat/admin.py
  chat/consumers.py
  chat/models.py
  chat/routing.py
  chat/serializers.py
  chat/urls.py
  chat/views.py
  joongobooks/asgi.py
  joongobooks/settings.py
  joongobooks/urls.py
  recommend/__init__.py
  recommend/admin.py
  recommend/apps.py
  recommend/models.py
  recommend/serializers.py
  recommend/tests.py
  recommend/urls.py
  recommend/views.py
Labels: enhancement, code insert

#45 📝 Docs : README ERD, 개발 에러 작성
  README.md
  readme/erd.png
Labels: 문서

#46 📝 Docs : 소감 수정
  README.md
Labels: 문서

#47 📝 Docs : URL 표 추가
  README.md
Labels: 문서

#49 README 추가
  README.md
Labels: 문서

#50 requirement.txt 파일 수정 PR 입니다
  requirements.txt
Labels: enhancement

#52 📝 Docs : Readme 수정
  README.md
  readme/pem.png
Labels: 문서

#54 9/11 user, profile 모델 병합
  joongobooks/settings.py
  user/admin.py
  user/models.py
  user/serializers.py
  user/urls.py
  user/views.py
Labels: Refator, code change

#68 ✨ Feat : 비밀번호 찾기(재설정) 기능 추가
  user/urls.py
  user/views.py
Labels: code insert, 고도화작업

#69 ♻️ Refactor : ProfileUpdate 리팩토링 PR입니다
  book/models.py
  readme/github-issueboard.png
  readme/notionplanner.png
  user/serializers.py
  user/urls.py
  user/views.py
Labels: Refator, code change, 고도화작업

#71 ✨ Feat : Book review update
  bookreview/__init__.py
  bookreview/admin.py
  bookreview/apps.py
  bookreview/models.py
  bookreview/serializers.py
  bookreview/tests.py
  bookreview/urls.py
  bookreview/views.py
  joongobooks/settings.py
  joongobooks/urls.py
Labels: enhancement, code insert, 고도화작업

#72 🐛 Fix : 판매자 닉네임 오류 수정
  book/serializers.py
  book/views.py
Labels: 버그수정, Refator, 고도화작업

#75 ♻️ Refactor : 좋아요 기능 메서드 변경 및 user모델 nickname필드 옵션 재변경
  book/models.py
  book/serializers.py
  book/urls.py
  book/views.py
  readme/github-issueboard.png
  readme/notionplanner.png
  user/models.py
  user/serializers.py
  user/urls.py
  user/views.py
Labels: enhancement, Refator, code change, 고도화작업

#77 ♻️ Refactor : User model 및 Profile 코드 리팩토링
  user/models.py
  user/serializers.py
  user/urls.py
  user/views.py
Labels: 버그수정, code insert, code remove, Refator, code change, 고도화작업

#80 ♻️ Refactor : 도서 서평 기능 구현 및 리팩토링
  bookreview/__init__.py
  bookreview/admin.py
  bookreview/apps.py
  bookreview/models.py
  bookreview/serializers.py
  bookreview/tests.py
  bookreview/urls.py
  bookreview/views.py
  joongobooks/settings.py
  joongobooks/urls.py
Labels: 버그수정, enhancement, code insert, code remove, Refator, code change, 고도화작업

#81 ✨Feat : 좋아요기능(이미 좋아요를 했는지 확인여부)추가 및 좋아요취소기능
  book/models.py
  book/urls.py
  book/views.py
Labels: enhancement, code insert, 고도화작업
