Repository silent-readers/joogobooks_back, pull requests merged in 2023-08, with the labels that each got.

#1 ✨ Feat : Model, Serializer 추가
  book/models.py
  book/serializers.py
Labels: enhancement

#2 8/21 프로필기능(프로필 조회, 프로필 생성)구현
  joongobooks/settings.py
  user/admin.py
  user/models.py
  user/serializers.py
  user/urls.py
  user/views.py
Labels: enhancement

#13 ✨ profile get메서드 구현, admin profile 추가
  user/admin.py
  user/views.py
Labels: enhancement

#14 ✨ Feat : Book create, list 기능 추가 및 모델 수정
  book/admin.py
  book/models.py
  book/serializers.py
  book/urls.py
  book/views.py
  joongobooks/settings.py
  joongobooks/urls.py
  user/admin.py
  user/models.py
Labels: enhancement

#18 ✨ profile update 기능구현, url연결
  user/urls.py
  user/views.py
Labels: enhancement

#19 ♻️ Refactor : Book 이미지 업로드 루트 수정
  .gitignore
  book/models.py
  book/serializers.py
  book/views.py
  joongobooks/settings.py
Labels: enhancement

#20 Book
  .gitignore
  book/admin.py
  book/models.py
  book/serializers.py
  book/urls.py
  book/views.py
  joongobooks/settings.py
  joongobooks/urls.py
  user/admin.py
  user/models.py
Labels: enhancement

#21 User
  joongobooks/urls.py
  user/admin.py
  user/models.py
  user/serializers.py
  user/urls.py
  user/views.py
Labels: enhancement

#24 Book
  book/models.py
  book/serializers.py
  book/urls.py
  book/views.py
Labels: enhancement

#26 User
  joongobooks/urls.py
  user/urls.py
  user/views.py
Labels: enhancement

#27 ✨ Search 기능 추가, Pagination 적용
  book/pagination.py
  book/urls.py
  book/views.py
  joongobooks/settings.py
  requirements.txt
Labels: enhancement

#29 ✨ Book Review 기능
  bookreview/__init__.py
  bookreview/admin.py
  bookreview/apps.py
  bookreview/models.py
  bookreview/serializers.py
  bookreview/tests.py
  bookreview/urls.py
  bookreview/views.py
  joongobooks/settings.py
  joongobooks/urls.py
Labels: enhancement

#31 ✨ Feat : 구매기록, 판매기록, 후기 기능 추가
  bookreview/models.py
  bookreview/serializers.py
  bookreview/views.py
  user/models.py
  user/urls.py
  user/views.py
Labels: enhancement

#37 🐛 Fix : 글 수정 및 삭제 권한 변경, 판매 기록 접근 권한 변경
  book/views.py
  user/views.py
Labels: enhancement

#36 ♻️ BookSearchView 권한 수정
  book/views.py
Labels: code change

#38 8/30 찜추가기능 PR입니다
  jjim/__init__.py
  jjim/admin.py
  jjim/apps.py
  jjim/models.py
  jjim/serializers.py
  jjim/tests.py
  jjim/urls.py
  jjim/views.py
  joongobooks/settings.py
  joongobooks/urls.py
Labels: enhancement

#39 ♻️ view_count 접근 수정
  bookreview/serializers.py
Labels: code insert

#40 Jjim 삭제기능 구현 PR입니다
  jjim/__init__.py
  jjim/admin.py
  jjim/apps.py
  jjim/models.py
  jjim/serializers.py
  jjim/tests.py
  jjim/urls.py
  jjim/views.py
  joongobooks/settings.py
  joongobooks/urls.py
Labels: enhancement

#42 Merge pull request #38 from k2h2j3/jjim
  jjim/views.py
Labels: enhancement
